markdown: rdiscount
pygments: true
permalink: /archive/:year/:title.html
rdiscount:
  extensions: [smart]

name: Shashank Mehta
url: http://shashankmehta.in
description: A fantastic blog that is fantastic.
twitter: holman
github: holman
gravatar_url: http://www.gravatar.com/avatar/91d05b8aab2671b4abc8a8c76435bf5a

disqus_short_name: leostatic
disqus_show_comment_count: false